// Query to display User Assignments changes on a Conditional Access Policy
// Can be used to monitor assignment changes for BGA or other specific accounts
// Note: "AssignmentChanges" only displays first matched condition (Added/Removed) however both changes may exist 

let AccountIds = dynamic([""]);
AuditLogs
| where TimeGenerated > ago (7d)
| where OperationName == "Update conditional access policy"
| mv-expand TGTResources = TargetResources[0].modifiedProperties
| extend newValue = parse_json(tostring(TGTResources.newValue))
| extend oldValue = parse_json(tostring(TGTResources.oldValue))
// Identify Current + Previous Users assigned to policy...
| extend nvExcludeUsers = newValue.conditions.users.excludeUsers
| extend nvIncludeUsers = newValue.conditions.users.includeUsers
| extend ovExcludeUsers = oldValue.conditions.users.excludeUsers
| extend ovIncludeUsers = oldValue.conditions.users.includeUsers
// Identify Users Added/Removed from policy...
| extend AddedExcludeUsers = set_difference(nvExcludeUsers, ovExcludeUsers)
| extend AddedIncludeUsers = set_difference(nvIncludeUsers, ovIncludeUsers)
| extend RemovedExcludeUsers = set_difference(ovExcludeUsers, nvExcludeUsers)
| extend RemovedIncludeUsers = set_difference(ovIncludeUsers, nvIncludeUsers)
// Create filter to Identify Assignment Changes...
| extend AssignmentChanges = case(AddedExcludeUsers has_any (AccountIds), "Added as Excluded User",
    AddedIncludeUsers has_any (AccountIds), "Added as Included User",
    RemovedExcludeUsers has_any (AccountIds), "Removed from Excluded Users",
    RemovedIncludeUsers has_any (AccountIds), "Removed from Included Users",
    "0")
| where AssignmentChanges != "0"
| extend PolicyName = TargetResources[0].displayName
| extend Actor = coalesce((InitiatedBy.user).userPrincipalName, (InitiatedBy.app).displayName)
| project-reorder TimeGenerated, PolicyName, Actor, AssignmentChanges, AddedExcludeUsers, AddedIncludeUsers, RemovedExcludeUsers, RemovedIncludeUsers
