// Check for group membership changes on PIM Role Assigned groups
// Obtains list of groups by checking for select PIM role activations

let PIMRoles = dynamic([""]);
let AzureAssignedGroups = AuditLogs
    | where TimeGenerated > ago (30d)
    | where OperationName == "Add member to role completed (PIM activation)"
    | where parse_json(tostring(TargetResources[0].displayName)) has_any (PIMRoles)
    | mv-expand TGTResources = TargetResources
    | where TGTResources.type == "Group"
    | extend RoleEnabledGroup = tostring(TGTResources.displayName)
    | distinct RoleEnabledGroup;
AzureAssignedGroups
| join kind=inner (AuditLogs
    | where TimeGenerated > ago (90d) 
    | where OperationName has_any ("Add member to group", "Remove member from group")
    | where parse_json(tostring(InitiatedBy.app)).displayName != "MS-PIM"
    | extend EntraRoleEnabledGroup = iff(isnotnull(TargetResources[0].modifiedProperties[1].newValue),
        parse_json(tostring(TargetResources[0].modifiedProperties[1].newValue)),
        parse_json(tostring(TargetResources[0].modifiedProperties[1].oldValue)))
    | extend EntraRoleEnabledGroup = tostring(EntraRoleEnabledGroup)
    | extend ChangedBy = coalesce((InitiatedBy.user).userPrincipalName, Identity)
    | extend AccountModified = TargetResources[0].userPrincipalName
) on $left.RoleEnabledGroup == $right.EntraRoleEnabledGroup
| project TimeGenerated, EntraRoleEnabledGroup, OperationName, AccountModified, ChangedBy









// OLD QUERY - See above for improved query; may contain incorrect or outdated references

let PIMRoles = dynamic([
    "Global Administrator", "Privileged Authentication Administrator", "Privileged Role Administrator",
    "Security Administrator", "Conditional Access Administrator", "Authentication Administrator"]);
let AzureAssignedGroups = AuditLogs
    | where TimeGenerated > ago (7d)
    | where OperationName == "Add member to role completed (PIM activation)"
    | where parse_json(tostring(TargetResources[0].displayName)) has_any (PIMRoles)
    | where isnotempty(TargetResources[6])
    | extend PimGroup = iif(isnotempty(TargetResources[6].displayName),
        TargetResources[6].displayName,
        TargetResources[7].displayName)
    | distinct tostring(PimGroup);
AzureAssignedGroups
| join kind=inner (AuditLogs
    | where TimeGenerated > ago (30d) 
    | where OperationName == "Add member to group" or OperationName == "Remove member from group"
    | extend AzureRoleEnabledGroup = iff(isnotnull(TargetResources[0].modifiedProperties[1].newValue),
        parse_json(tostring(TargetResources[0].modifiedProperties[1].newValue)),
        parse_json(tostring(TargetResources[0].modifiedProperties[1].oldValue)))
    | extend AzureRoleEnabledGroup = tostring(AzureRoleEnabledGroup)
    | extend ChangedBy = (InitiatedBy.user).userPrincipalName
) on $left.PimGroup == $right.AzureRoleEnabledGroup
| project TimeGenerated, AzureRoleEnabledGroup, OperationName, ChangedBy
