// Query to track users/groups being added to PIM Managed Groups
// Returns basic summary of changes made

AuditLogs
| where TimeGenerated > ago (7d)
| where OperationName in~("Add eligible member to role in PIM completed (permanent)", "Add member to role in PIM completed (permanent)")
| where TargetResources[3].type has_any("Group", "User")
| where TargetResources[0].displayName == "Member"
| extend Group = TargetResources[2].displayName
| extend ObjectAdded = TargetResources[3].displayName
| extend AccountUPN = TargetResources[3].userPrincipalName
| extend ChangedBy = InitiatedBy.user.userPrincipalName
| project TimeGenerated, OperationName, Group, ObjectAdded, AccountUPN, ChangedBy
