// Query to display changes to Group or User Assignments for a Conditional Access Policy
// This only targets Included/Excluded Users and Groups and does not include Role assignment
// Output displays Object IDs, manual lookup to identify Group or User is required
// Note: "AssignmentChanges" only displays first matched condition (Added/Removed) however both changes may exist 

AuditLogs
| where TimeGenerated > ago (7d)
| where OperationName == "Update conditional access policy"
| where ResultDescription != "Restored soft deleted conditional access policy"
| mv-expand TGTResources = TargetResources[0].modifiedProperties
| where TGTResources has_any ("excludeGroups", "includeGroups")
| extend newValue = parse_json(tostring(TGTResources.newValue))
| extend oldValue = parse_json(tostring(TGTResources.oldValue))
// Identify current Groups + Users assigned to policy... 
| extend nvExcludeGroups = newValue.conditions.users.excludeGroups,
    nvIncludeGroups = newValue.conditions.users.includeGroups,
    nvExcludeUsers = newValue.conditions.users.excludeUsers,
    nvIncludeUsers = newValue.conditions.users.includeUsers
// Identify previous Groups + Users assigned to policy...
| extend ovExcludeGroups = oldValue.conditions.users.excludeGroups,
    ovIncludeGroups = oldValue.conditions.users.includeGroups,
    ovExcludeUsers = oldValue.conditions.users.excludeUsers,
    ovIncludeUsers = oldValue.conditions.users.includeUsers
// Identify Groups + Users that were added to policy...
| extend AddedExcludeGroups = set_difference(nvExcludeGroups, ovExcludeGroups), 
    AddedIncludeGroups = set_difference(nvIncludeGroups, ovIncludeGroups),
    AddedExcludeUsers = set_difference(nvExcludeUsers, ovExcludeUsers),
    AddedIncludeUsers = set_difference(nvIncludeUsers, ovIncludeUsers)
// Identify Groups + Users that were removed from policy...
| extend RemovedExcludeGroups = set_difference(ovExcludeGroups, nvExcludeGroups),
    RemovedIncludeGroups = set_difference(ovIncludeGroups, nvIncludeGroups),
    RemovedExcludeUsers = set_difference(ovExcludeUsers, nvExcludeUsers),
    RemovedIncludeUsers = set_difference(ovIncludeUsers, nvIncludeUsers)
// Create Filter to Identify Assignment Changes...
| extend AssignmentChanges = case(AddedExcludeGroups != "[]", "Group or User Added to policy assignment",
    AddedIncludeGroups != "[]", "Group or User Added to policy assignment", 
    AddedExcludeUsers != "[]", "Group or User Added to policy assignment",
    AddedIncludeUsers != "[]", "Group or User Added to policy assignment",
    RemovedExcludeGroups != "[]", "Group or User Removed from policy assignment",
    RemovedIncludeGroups != "[]", "Group or User Removed from policy assignment",
    RemovedExcludeUsers != "[]", "Group or User Removed from policy assignment",
    RemovedIncludeUsers != "[]", "Group or User Removed from policy assignment",
    "0")
// Filter out events that did not include User/Group Assignment Changes
| where AssignmentChanges != "0"
| extend PolicyName = TargetResources[0].displayName
| extend Actor = coalesce((InitiatedBy.user).userPrincipalName, (InitiatedBy.app).displayName)
| project TimeGenerated, PolicyName, Actor, AssignmentChanges, AddedExcludeGroups, AddedIncludeGroups, AddedExcludeUsers, AddedIncludeUsers, 
RemovedExcludeGroups, RemovedIncludeGroups,  RemovedExcludeUsers, RemovedIncludeUsers
