// Query to track users and groups added to PIM role assignments
// Returns basic summary of changes made

AuditLogs
| where TimeGenerated > ago (7d)
| where OperationName in~("Add eligible member to role in PIM completed (permanent)", "Add member to role in PIM completed (permanent)", "Add member to role in PIM completed (timebound)")
| where TargetResources[3].type has_any("Group", "User")
| where TargetResources[0].displayName != "Member"
| extend ChangedBy = InitiatedBy.user.userPrincipalName
| extend EntraRole = TargetResources[0].displayName
| extend ObjectAdded = TargetResources[3].displayName
| extend AccountUPN = TargetResources[3].userPrincipalName
| parse AdditionalDetails with * 'Justification","value":"' Justification '"' *
| project TimeGenerated, OperationName, EntraRole, ObjectAdded, AccountUPN, Justification, ChangedBy
